# Site settings
exclude: attic
title: Luna Sky - Action Platform Game
subtitle: by Vovoid Media Technologies AB
email: youremailaddress@gmail.com
description: Play as Luna on her mission to help the stranded humans<br/>Experience action, puzzles and blistering fast platforming in 5 diverse levels<br/><br/>V2.0 out now!<br/>2017-10-10
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://new.vsxu.com" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:
current_version: v0.6.0
current_version_date: 2017-04-02

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://www.facebook.com/VovoidVSXu
github_url: https://github.com/vovoid/vsxu
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/VSXu
twitch_url: https://www.twitch.tv/vmediatech
reddit_url: https://www.reddit.com/r/VSXu/
youtube_url: https://www.youtube.com/user/VSXu

# Build settings
markdown: kramdown

sass:
  style: compressed
