# Site settings
exclude: attic
title: Luna Sky - Action Platform Game
subtitle: by Vovoid Media Technologies AB
email: youremailaddress@gmail.com
description: Version 2.0 in development!<br><br>Look forward to help Luna in her mission<br/>Experience speedy action, puzzles and thrilling gameplay in 5 diverse worlds<br/><br/>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://new.lunasky.vovoid.com" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:
current_version: v1.5
current_version_date: 2016-04-02

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://www.facebook.com/LunaSkyGame
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/LunaSkyGame
twitch_url: https://www.twitch.tv/vmediatech
reddit_url:
youtube_url: https://www.youtube.com/user/VSXu

# Build settings
markdown: kramdown

sass:
  style: compressed
